name: Update GitOps repo
on:
  workflow_dispatch:

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: kiranvinod-02/argocd-gitops-demo
          token: ${{ secrets.GITOPS_REPO_PAT }}
          path: gitops

      - name: Bump replica count
        run: |
          cd gitops
          sed -i 's/replicaCount: .*/replicaCount: 3/' online-shop-chart/values.yaml

      - name: Commit and push
        run: |
          cd gitops
          git config user.name "ci-bot"
          git config user.email "ci-bot@example.com"
          git add .
          git commit -m "CI: bump replicaCount to 3"
          git push
